-- MySQL Script generated by MySQL Workbench
-- 03/05/15 16:58:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`organType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`organType` (
  `organTypeID` INT NOT NULL,
  `organName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`organTypeID`),
  UNIQUE INDEX `organTypeID_UNIQUE` (`organTypeID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BloodType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BloodType` (
  `bloodTypeID` INT NOT NULL,
  `BloodTypeName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`bloodTypeID`),
  UNIQUE INDEX `bloodTypeID_UNIQUE` (`bloodTypeID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recipient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recipient` (
  `RecipientID` INT NOT NULL AUTO_INCREMENT,
  `MedicalPersonnelID` INT NOT NULL,
  `severity` ENUM('1', '2', '3', '4,') NOT NULL,
  `OriginalID` VARCHAR(50) NULL,
  `gender` ENUM('M', 'F') NOT NULL,
  `age` INT NOT NULL,
  `dateRegistered` DATETIME NOT NULL,
  `endDate` DATETIME NULL,
  `Organs_organID` INT NULL,
  `organType_organTypeID` INT NOT NULL,
  `BloodType_bloodTypeID` INT NOT NULL,
  PRIMARY KEY (`RecipientID`),
  UNIQUE INDEX `RecipientID_UNIQUE` (`RecipientID` ASC),
  INDEX `fk_Recipient_Organs1_idx` (`Organs_organID` ASC),
  INDEX `fk_Recipient_organType1_idx` (`organType_organTypeID` ASC),
  INDEX `fk_Recipient_BloodType1_idx` (`BloodType_bloodTypeID` ASC),
  CONSTRAINT `fk_Recipient_Organs1`
    FOREIGN KEY (`Organs_organID`)
    REFERENCES `mydb`.`Organs` (`OrganID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recipient_organType1`
    FOREIGN KEY (`organType_organTypeID`)
    REFERENCES `mydb`.`organType` (`organTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recipient_BloodType1`
    FOREIGN KEY (`BloodType_bloodTypeID`)
    REFERENCES `mydb`.`BloodType` (`bloodTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Organs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Organs` (
  `OrganID` INT NOT NULL AUTO_INCREMENT,
  `organType_organTypeID` INT NOT NULL,
  `BloodType_bloodTypeID` INT NOT NULL,
  `DateAcquired` DATETIME NOT NULL,
  `expirationDate` DATETIME NOT NULL,
  `MedicalPersonnelID` INT NOT NULL,
  `OriginalID` VARCHAR(50) NULL,
  `available` TINYINT(1) NOT NULL,
  `Recipient_RecipientID` INT NULL,
  `DonorID` INT NOT NULL,
  PRIMARY KEY (`OrganID`),
  UNIQUE INDEX `organID_UNIQUE` (`OrganID` ASC),
  INDEX `fk_Organs_Recipient1_idx` (`Recipient_RecipientID` ASC),
  INDEX `fk_Organs_organType1_idx` (`organType_organTypeID` ASC),
  INDEX `fk_Organs_BloodType1_idx` (`BloodType_bloodTypeID` ASC),
  CONSTRAINT `fk_Organs_Recipient1`
    FOREIGN KEY (`Recipient_RecipientID`)
    REFERENCES `mydb`.`Recipient` (`RecipientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Organs_organType1`
    FOREIGN KEY (`organType_organTypeID`)
    REFERENCES `mydb`.`organType` (`organTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Organs_BloodType1`
    FOREIGN KEY (`BloodType_bloodTypeID`)
    REFERENCES `mydb`.`BloodType` (`bloodTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`State`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`State` (
  `StateID` INT NOT NULL,
  `State` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`StateID`),
  UNIQUE INDEX `organTypeId_UNIQUE` (`StateID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`City` (
  `CityID` INT NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `State_StateID` INT NOT NULL,
  PRIMARY KEY (`CityID`),
  UNIQUE INDEX `organTypeId_UNIQUE` (`CityID` ASC),
  INDEX `fk_City_State1_idx` (`State_StateID` ASC),
  CONSTRAINT `fk_City_State1`
    FOREIGN KEY (`State_StateID`)
    REFERENCES `mydb`.`State` (`StateID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medical_Personnel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medical_Personnel` (
  `userName` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `MedicalPersonnelID` INT NOT NULL AUTO_INCREMENT,
  `medicalFacility` VARCHAR(50) NOT NULL,
  `contactEmail` VARCHAR(50) NOT NULL,
  `phoneNumber` INT NOT NULL,
  `validatedUser` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT TIMESTAMP,
  `State_StateID` INT NOT NULL,
  `City_CityID` INT NOT NULL,
  PRIMARY KEY (`MedicalPersonnelID`),
  UNIQUE INDEX `MedicalPersonnelID_UNIQUE` (`MedicalPersonnelID` ASC),
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC),
  INDEX `fk_Medical Personnel_State1_idx` (`State_StateID` ASC),
  INDEX `fk_Medical Personnel_City1_idx` (`City_CityID` ASC),
  CONSTRAINT `fk_Medical Personnel_State1`
    FOREIGN KEY (`State_StateID`)
    REFERENCES `mydb`.`State` (`StateID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medical Personnel_City1`
    FOREIGN KEY (`City_CityID`)
    REFERENCES `mydb`.`City` (`CityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medical Personnel_has_Recipient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medical Personnel_has_Recipient` (
  `Medical_Personnel_MedicalPersonnelID` INT NOT NULL,
  `Recipient_RecipientID` INT NOT NULL,
  PRIMARY KEY (`Medical_Personnel_MedicalPersonnelID`, `Recipient_RecipientID`),
  INDEX `fk_Medical Personnel_has_Recipient_Recipient1_idx` (`Recipient_RecipientID` ASC),
  INDEX `fk_Medical Personnel_has_Recipient_Medical Personnel_idx` (`Medical_Personnel_MedicalPersonnelID` ASC),
  CONSTRAINT `fk_Medical Personnel_has_Recipient_Medical Personnel`
    FOREIGN KEY (`Medical_Personnel_MedicalPersonnelID`)
    REFERENCES `mydb`.`Medical_Personnel` (`MedicalPersonnelID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medical Personnel_has_Recipient_Recipient1`
    FOREIGN KEY (`Recipient_RecipientID`)
    REFERENCES `mydb`.`Recipient` (`RecipientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Donor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Donor` (
  `DonorID` INT NOT NULL AUTO_INCREMENT,
  `age` INT NOT NULL,
  `gender` ENUM('M','F') NOT NULL,
  `registrationDate` DATETIME NOT NULL,
  `endDate` DATETIME NULL,
  `MedicalPersonnelID` INT NOT NULL,
  `phoneNumber` INT NOT NULL,
  `originalID` VARCHAR(50) NULL,
  PRIMARY KEY (`DonorID`),
  UNIQUE INDEX `DonorID_UNIQUE` (`DonorID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medical Personnel_has_Donors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medical Personnel_has_Donors` (
  `Medical_Personnel_MedicalPersonnelID` INT NOT NULL,
  `Donor_DonorID` INT NOT NULL,
  PRIMARY KEY (`Medical_Personnel_MedicalPersonnelID`, `Donor_DonorID`),
  INDEX `fk_Medical Personnel_has_Donors_Medical Personnel1_idx` (`Medical_Personnel_MedicalPersonnelID` ASC),
  INDEX `fk_Medical Personnel_has_Donors_Donors1_idx` (`Donor_DonorID` ASC),
  CONSTRAINT `fk_Medical Personnel_has_Donors_Medical Personnel1`
    FOREIGN KEY (`Medical_Personnel_MedicalPersonnelID`)
    REFERENCES `mydb`.`Medical_Personnel` (`MedicalPersonnelID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medical Personnel_has_Donors_DonorID`
    FOREIGN KEY (`Donor_DonorID`)
    REFERENCES `mydb`.`Donor` (`DonorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrganExpirationTime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrganExpirationTime` (
  `organType_organTypeID` INT NOT NULL,
  `TimeUntilExpiration` TIME NOT NULL,
  INDEX `fk_OrganExpirationTime_organType1_idx` (`organType_organTypeID` ASC),
  CONSTRAINT `fk_OrganExpirationTime_organType1`
    FOREIGN KEY (`organType_organTypeID`)
    REFERENCES `mydb`.`organType` (`organTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Donor_has_Organs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Donor_has_Organs` (
  `Organs_OrganID` INT NOT NULL,
  `Donor_DonorID` INT NOT NULL,
  PRIMARY KEY (`Organs_OrganID`, `Donor_DonorID`),
  INDEX `fk_Donor_has_Organs_Organs1_idx` (`Organs_OrganID` ASC),
  INDEX `fk_Donor_has_Organs_Donor1_idx` (`Donor_DonorID` ASC),
  CONSTRAINT `fk_Donor_has_Organs_Organs1`
    FOREIGN KEY (`Organs_OrganID`)
    REFERENCES `mydb`.`Organs` (`OrganID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Donor_has_Organs_Donor1`
    FOREIGN KEY (`Donor_DonorID`)
    REFERENCES `mydb`.`Donor` (`DonorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
