-- MySQL Script generated by MySQL Workbench
-- 03/05/15 18:57:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sql369493
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sql369493
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sql369493` DEFAULT CHARACTER SET latin1 ;
USE `sql369493` ;

-- -----------------------------------------------------
-- Table `sql369493`.`BloodType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql369493`.`BloodType` (
  `bloodTypeID` INT(11) NOT NULL AUTO_INCREMENT,
  `bloodTypeName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`bloodTypeID`),
  UNIQUE INDEX `bloodTypeID_UNIQUE` (`bloodTypeID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sql369493`.`State`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql369493`.`State` (
  `stateID` INT(11) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`stateID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sql369493`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql369493`.`City` (
  `cityID` INT(11) NOT NULL AUTO_INCREMENT,
  `stateStateID` INT(11) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cityID`),
  INDEX `fk_State_stateID_ibfk_1` (`stateStateID` ASC),
  CONSTRAINT `fk_State_stateID_ibfk_1`
    FOREIGN KEY (`stateStateID`)
    REFERENCES `sql369493`.`State` (`stateID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sql369493`.`Medical_Personnel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql369493`.`Medical_Personnel` (
  `medicalPersonnelId` INT(11) NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(20) NOT NULL,
  `userPassword` VARCHAR(20) NOT NULL,
  `medicalFacility` VARCHAR(20) NOT NULL,
  `contactEmail` VARCHAR(50) NOT NULL,
  `phoneNumber` INT(11) NOT NULL,
  `validatedUser` TINYINT(1) NOT NULL,
  `create_time` DATETIME NOT NULL,
  `State_StateID` INT(11) NOT NULL,
  `City_CityID` INT(11) NOT NULL,
  PRIMARY KEY (`medicalPersonnelId`),
  UNIQUE INDEX `medicalPersonnelId_UNIQUE` (`medicalPersonnelId` ASC),
  INDEX `Medical_Personnel_ibfk_1` (`State_StateID` ASC),
  INDEX `Medical_Personnel_ibfk_2` (`City_CityID` ASC),
  CONSTRAINT `Medical_Personnel_ibfk_1`
    FOREIGN KEY (`State_StateID`)
    REFERENCES `sql369493`.`State` (`stateID`),
  CONSTRAINT `Medical_Personnel_ibfk_2`
    FOREIGN KEY (`City_CityID`)
    REFERENCES `sql369493`.`City` (`cityID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sql369493`.`Donor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql369493`.`Donor` (
  `DonorID` INT(11) NOT NULL AUTO_INCREMENT,
  `phoneNumber` INT(11) NOT NULL,
  `registrationDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `endDate` TIMESTAMP NULL DEFAULT NULL,
  `medicalPersonnelId` INT(11) NOT NULL,
  `originalID` VARCHAR(50) NOT NULL,
  `gender` ENUM('M','F') NOT NULL,
  `age` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`DonorID`),
  UNIQUE INDEX `DonorID` (`DonorID` ASC),
  INDEX `fk_Donor_medicalPersonnelID_idx` (`medicalPersonnelId` ASC),
  CONSTRAINT `fk_Donor_medicalPersonnelID`
    FOREIGN KEY (`medicalPersonnelId`)
    REFERENCES `sql369493`.`Medical_Personnel` (`medicalPersonnelId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sql369493`.`OrganType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql369493`.`OrganType` (
  `organTypeID` INT(11) NOT NULL AUTO_INCREMENT,
  `organName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`organTypeID`),
  UNIQUE INDEX `organTypeID_UNIQUE` (`organTypeID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sql369493`.`Recipients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql369493`.`Recipients` (
  `recipentID` INT(11) NOT NULL AUTO_INCREMENT,
  `medicalPersonnelID` INT(11) NOT NULL,
  `severity` ENUM('1','2','3','4') NOT NULL,
  `orignialID` VARCHAR(50) NULL DEFAULT NULL,
  `gender` ENUM('M','F') NOT NULL,
  `dateRegistered` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `age` INT(11) UNSIGNED NOT NULL,
  `organsOrganID` INT(11) NULL DEFAULT NULL,
  `organTypeOrganTypeID` INT(11) NOT NULL,
  `bloodTypeBloodTypeID` INT(11) NOT NULL,
  PRIMARY KEY (`recipentID`),
  INDEX `fk_Medical_Personnel_medicalPersonnel_idx` (`medicalPersonnelID` ASC),
  INDEX `fk_BloodType_BloodType1_idx` (`bloodTypeBloodTypeID` ASC),
  INDEX `fk_organ_organID_idx_idx` (`organsOrganID` ASC),
  INDEX `fk_organType_organTypeID_ibfk_1` (`organTypeOrganTypeID` ASC),
  CONSTRAINT `fk_BloodType_BloodType1_idx`
    FOREIGN KEY (`bloodTypeBloodTypeID`)
    REFERENCES `sql369493`.`BloodType` (`bloodTypeID`),
  CONSTRAINT `fk_Medical_Personnel_medicalPersonnel_idx`
    FOREIGN KEY (`medicalPersonnelID`)
    REFERENCES `sql369493`.`Medical_Personnel` (`medicalPersonnelId`),
  CONSTRAINT `fk_organType_organTypeID_ibfk_1`
    FOREIGN KEY (`organTypeOrganTypeID`)
    REFERENCES `sql369493`.`OrganType` (`organTypeID`),
  CONSTRAINT `fk_organ_organID_idx`
    FOREIGN KEY (`organsOrganID`)
    REFERENCES `sql369493`.`Organs` (`OrganID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sql369493`.`Organs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql369493`.`Organs` (
  `OrganID` INT(11) NOT NULL AUTO_INCREMENT,
  `organType_organtypeID` INT(11) NOT NULL,
  `BloodType_BloodTypeID` INT(11) NOT NULL,
  `dateAqcuired` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `expirationDate` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `MedicalPersonnelID` INT(11) NOT NULL,
  `OrginalID` VARCHAR(50) NOT NULL,
  `available` TINYINT(1) NOT NULL,
  `Recipient_RecipientID` INT(11) NOT NULL,
  `OriginalID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`OrganID`),
  UNIQUE INDEX `OrganID_UNIQUE` (`OrganID` ASC),
  INDEX `Organs_RecipientID_idx` (`Recipient_RecipientID` ASC),
  INDEX `Organs_MedicalPersonnel_idx` (`MedicalPersonnelID` ASC),
  INDEX `Organs_BloodType_idx` (`BloodType_BloodTypeID` ASC),
  INDEX `Organs_organType_idx` (`organType_organtypeID` ASC),
  CONSTRAINT `Organs_BloodType`
    FOREIGN KEY (`BloodType_BloodTypeID`)
    REFERENCES `sql369493`.`BloodType` (`bloodTypeID`),
  CONSTRAINT `Organs_MedicalPersonnel`
    FOREIGN KEY (`MedicalPersonnelID`)
    REFERENCES `sql369493`.`Medical_Personnel` (`medicalPersonnelId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Organs_organType`
    FOREIGN KEY (`organType_organtypeID`)
    REFERENCES `sql369493`.`OrganType` (`organTypeID`),
  CONSTRAINT `Organs_RecipientID`
    FOREIGN KEY (`Recipient_RecipientID`)
    REFERENCES `sql369493`.`Recipients` (`recipentID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sql369493`.`Donor_has_Organs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql369493`.`Donor_has_Organs` (
  `Organ_OrganID` INT(11) NOT NULL,
  `Donor_DonorID` INT(11) NOT NULL,
  INDEX `Donor_DonorID_idx` (`Donor_DonorID` ASC),
  INDEX `Organ_OrganID` (`Organ_OrganID` ASC),
  CONSTRAINT `Organ_OrganID`
    FOREIGN KEY (`Organ_OrganID`)
    REFERENCES `sql369493`.`Organs` (`OrganID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Donor_DonorID`
    FOREIGN KEY (`Donor_DonorID`)
    REFERENCES `sql369493`.`Donor` (`DonorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sql369493`.`Medical_Personnnel_has_Donors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql369493`.`Medical_Personnnel_has_Donors` (
  `Medical_Personnel_medicalPersonnelID` INT(11) NOT NULL,
  `Donor_DonorID` INT(11) NOT NULL,
  INDEX `fk_Medical_Personnel_has_Donors_Medical_Personnel1_idx_idx` (`Medical_Personnel_medicalPersonnelID` ASC),
  INDEX `fk_Medical_Personnel_has_Donors_Donors1_idx_idx` (`Donor_DonorID` ASC),
  CONSTRAINT `fk_Medical_Personnel_has_Donors_Medical_Personnel1_idx`
    FOREIGN KEY (`Medical_Personnel_medicalPersonnelID`)
    REFERENCES `sql369493`.`Medical_Personnel` (`medicalPersonnelId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medical_Personnel_has_Donors_Donors1_idx`
    FOREIGN KEY (`Donor_DonorID`)
    REFERENCES `sql369493`.`Donor` (`DonorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sql369493`.`Medical_Personnnel_has_Recipients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql369493`.`Medical_Personnnel_has_Recipients` (
  `Medical_Personnel_medicalPersonnelID` INT(11) NOT NULL,
  `Recipient_recipientID` INT(11) NOT NULL,
  INDEX `fk_Medical_Personnel_has_Recipients1_idx_idx` (`Recipient_recipientID` ASC),
  INDEX `fk_Medical_Personnel_has_Medical_Personnel1_idx_idx` (`Medical_Personnel_medicalPersonnelID` ASC),
  CONSTRAINT `fk_Medical_Personnel_has_Recipients1_idx`
    FOREIGN KEY (`Recipient_recipientID`)
    REFERENCES `sql369493`.`Recipients` (`recipentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medical_Personnel_has_Medical_Personnel1_idx`
    FOREIGN KEY (`Medical_Personnel_medicalPersonnelID`)
    REFERENCES `sql369493`.`Medical_Personnel` (`medicalPersonnelId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sql369493`.`OrganExpirationTime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql369493`.`OrganExpirationTime` (
  `timeUntilExpiration` TIME NOT NULL,
  `organType_organTypeID` INT(11) NOT NULL,
  INDEX `fk_OrganExpirationTime_OrganTypeID_idx` (`organType_organTypeID` ASC),
  CONSTRAINT `fk_OrganExpirationTime_OrganType1`
    FOREIGN KEY (`organType_organTypeID`)
    REFERENCES `sql369493`.`OrganType` (`organTypeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
